
name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v5
       

    #   - name: Install dependencies
    #     run: npm install

    #   - name: Build the project
    #     run: npm run build

    #   - name: Run Cypress tests
    #     uses: cypress-io/github-action@v6
    #     with:
    #       start: npm start
    #       wait-on: 'http://localhost:3000' # Adjust port based on your app
