
name: Cypress Tests

on: 
   push:
   schedule:
     - cron: '30 6 * * 1-5'

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.0.5
    
      - name: Cypress run
        uses: cypress-io/github-action@v5
       

  
